#!/bin/sh
# CraftKit adapter: GitHub Copilot CLI
# Generates .github/skills/ck-*/SKILL.md skill shims per
# https://docs.github.com/en/copilot/how-tos/copilot-cli/customize-copilot/add-skills
# (invoked as /ck-<name> in the CLI) and a marked block in
# .github/copilot-instructions.md. AGENTS.md (generated by init) is the
# primary integration point — Copilot CLI reads it natively.
# Idempotent — safe to re-run via `craftkit sync`.
set -eu

REPO_ROOT="${1:-$(pwd)}"
KIT_DIR="$REPO_ROOT/.craftkit"
SKILLS_DIR="$REPO_ROOT/.github/skills"

[ -d "$KIT_DIR/skills" ] || { echo "copilot-cli adapter: $KIT_DIR/skills not found" >&2; exit 1; }

# Extract the frontmatter description from a skill/workflow file.
get_desc() {
  sed -n '2,10p' "$1" | sed -n 's/^description:[[:space:]]*"\{0,1\}//p' | head -1 | sed 's/"$//'
}

write_shim() { # $1=name $2=source-file $3=relative-target
  desc=$(get_desc "$2")
  [ -n "$desc" ] || desc="CraftKit $1"
  mkdir -p "$SKILLS_DIR/ck-$1"
  cat > "$SKILLS_DIR/ck-$1/SKILL.md" <<EOF
---
name: ck-$1
description: "$desc"
---
Read and follow \`$3\`.
EOF
}

mkdir -p "$SKILLS_DIR"
rm -rf "$SKILLS_DIR"/ck-*
# Migrate away from the pre-0.3 custom-agent shims.
rm -f "$REPO_ROOT/.github/agents"/ck-*.md
rmdir "$REPO_ROOT/.github/agents" 2>/dev/null || true

for wf in "$KIT_DIR"/workflows/*.md; do
  [ -f "$wf" ] || continue
  name=$(basename "$wf" .md)
  write_shim "$name" "$wf" "./.craftkit/workflows/$name.md"
done

for sk in "$KIT_DIR"/skills/*/SKILL.md; do
  [ -f "$sk" ] || continue
  name=$(basename "$(dirname "$sk")")
  [ "$name" = "references" ] && continue
  [ -f "$KIT_DIR/workflows/$name.md" ] && continue  # workflow owns this name
  write_shim "$name" "$sk" "./.craftkit/skills/$name/SKILL.md"
done

if [ -d "$REPO_ROOT/.craftkit-project/overrides" ]; then
  for ov in "$REPO_ROOT"/.craftkit-project/overrides/*/SKILL.md; do
    [ -f "$ov" ] || continue
    name=$(basename "$(dirname "$ov")")
    write_shim "$name" "$ov" "./.craftkit-project/overrides/$name/SKILL.md"
  done
fi

# copilot-instructions.md: maintain a regenerable marked block.
CI_MD="$REPO_ROOT/.github/copilot-instructions.md"
BLOCK=$(cat <<'EOF'
<!-- craftkit:begin (generated — do not edit; run `craftkit sync`) -->
## CraftKit

This repo uses CraftKit. Read `AGENTS.md` for the module registry, pipeline,
and critical rules — all rules there apply.

- Invoke workflows/skills via the `/ck-*` skills in `.github/skills/`.
- Work from local files only inside skills: no web access, no external tools.
- Load context on demand: only the skill for the current phase, the impacted
  module profiles, and the one upstream artifact.
- Artifacts must have `status: approved` before a downstream skill consumes
  them. Follow `.craftkit/skills/references/escalation-protocol.md` exactly.
<!-- craftkit:end -->
EOF
)
TMP=$(mktemp)
if [ -f "$CI_MD" ] && grep -q '<!-- craftkit:begin' "$CI_MD"; then
  awk '/<!-- craftkit:begin/{skip=1} !skip{print} /<!-- craftkit:end -->/{skip=0}' "$CI_MD" > "$TMP"
else
  [ -f "$CI_MD" ] && cat "$CI_MD" > "$TMP" || printf '# Copilot Instructions\n\n' > "$TMP"
fi
printf '%s\n' "$BLOCK" >> "$TMP"
mv "$TMP" "$CI_MD"

echo "copilot-cli adapter: $(ls -d "$SKILLS_DIR"/ck-* | wc -l | tr -d ' ') skill shims, copilot-instructions.md block updated"
